import { Disclaimer, Stack } from "@gykmi/ui";
import type { Meta, StoryObj } from "@storybook/react-vite";

const meta = {
	title: "POV/Disclaimer",
	component: Disclaimer,
	tags: ["autodocs"],
	argTypes: {
		variant: { control: "select", options: ["info", "warning", "regulatory"] },
	},
} satisfies Meta<typeof Disclaimer>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Info: Story = {
	args: {
		variant: "info",
		title: "AI-generated content",
		children:
			"This analysis was generated by an AI model and should be reviewed by a qualified professional before making investment decisions.",
	},
};

export const Warning: Story = {
	args: {
		variant: "warning",
		title: "Data limitations",
		children:
			"The underlying dataset covers January 2024 to June 2026 only. Extrapolations beyond this range carry increased uncertainty.",
	},
};

export const Regulatory: Story = {
	args: {
		variant: "regulatory",
		title: "Regulatory disclosure",
		children:
			"This report is produced under the supervision of authorised personnel in accordance with FCA SYSC 6.1. It does not constitute financial advice.",
	},
};

export const AllVariants: Story = {
	render: () => (
		<Stack gap="3">
			<Disclaimer variant="info" title="AI-generated content">
				Review before acting on this analysis.
			</Disclaimer>
			<Disclaimer variant="warning" title="Data limitations">
				Limited historical data available.
			</Disclaimer>
			<Disclaimer variant="regulatory" title="FCA disclosure">
				Not financial advice.
			</Disclaimer>
		</Stack>
	),
};
