import { readFileSync, writeFileSync } from "node:fs";

// Concatenate CSS files into a single tokens.css
const primitive = readFileSync("dist/tokens.primitive.css", "utf8");
const light = readFileSync("dist/tokens.light.css", "utf8");
const dark = readFileSync("dist/tokens.dark.css", "utf8");

const combined = `/* Generated by Style Dictionary — do not edit */\n\n${primitive}\n${light}\n${dark}\n`;

writeFileSync("dist/tokens.css", combined);

console.log("Generated dist/tokens.css");
